### ISSUE TITLE
Setup TypeScript

### ISSUE THREAD

**Issue by xeho91** [shan-shan-dev/shan-shan#12]
## Resources

- https://www.typescriptlang.org/tsconfig

## Tasks

- [x] Setup `tsconfig.json` at the root of this project
- [x] Setup `tsconfig.json` for every kind of package
- [x] Create a build workflow and include it in the CI workflow
