### ISSUE TITLE
Setup project workspace paths functions

### ISSUE THREAD

**Issue by xeho91** [shan-shan-dev/shan-shan#31]
### Resources

- [find-up](https://www.npmjs.com/package/find-up)

### Tasks

- [x] Add a function `findWorkspaceRootPath()`
- [x] Add a function `findAppRootPath(name)`
- [x] Add a function `findPackageRootPath(name)`
- [x] Write tests
