### ISSUE TITLE
Initial project config package

### ISSUE THREAD

**Issue by xeho91** [shan-shan-dev/shan-shan#34]
### Resources

- [dotenv](https://github.com/motdotla/dotenv)
- [znv](https://github.com/lostfictions/znv)
- [enquirer](https://github.com/enquirer/enquirer) for script CLI

### Tasks

- [ ] Create a script to automatically generate environment variables
- [ ] Create `loadConfig()` function
- [x] Use `dotenv` to create `loadDotenv()`
