### ISSUE TITLE
Setup database

### ISSUE THREAD

**Issue by xeho91** [shan-shan-dev/shan-shan#42]
### Resources

- ?

### Tasks

- [x] Define environment variables in `@packages/config`
- [ ] Create `seed` script
- [x] Setup CI for testing purposes
