### ISSUE TITLE
Remove prettier

### ISSUE THREAD

**Issue by xeho91** [shan-shan-dev/shan-shan#57]
### Resources

Once Biome has support for:

- Astro
- HTML
- Svelte

## Tracking

- https://biomejs.dev/internals/language-support/

### Tasks

- [ ] Remove `prettier.yml` workflow from the CI & CD
- [ ] Remove `fix:prettier` & `lint:prettier` from the `scripts` in `package.json` files
- [ ] Remove `prettier.config.js`
